In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'C:\\Users\\giank\\OneDrive\\Escritorio\\yerba-mate-analisi\\notebooks'

In [4]:
import pandas as pd

df = pd.read_csv("../data/yerba-mate-1970-2024.csv", encoding="latin-1")

df.head()

,cultivo,anio,campania,provincia,provincia_id,departamento,departamento_id,superficie_sembrada_ha,superficie_cosechada_ha,produccion_tm,rendimiento_kgxha
0,yerba mate,1970,1969/1970,Corrientes,18,Ituzaingó,18084,3470,1106,2375,2147
1,yerba mate,1970,1969/1970,Corrientes,18,Santo Tomé,18168,5205,1661,3564,2146
2,yerba mate,1970,1969/1970,Misiones,54,Apóstoles,54007,11784,3052,5150,1687
3,yerba mate,1970,1969/1970,Misiones,54,Cainguás,54014,6078,1566,3568,2278
4,yerba mate,1970,1969/1970,Misiones,54,Candelaria,54021,3298,872,1020,1170

In [6]:
df.shape

(1044, 11)

In [7]:
df.columns

Index(['cultivo', 'anio', 'campania', 'provincia', 'provincia_id',
       'departamento', 'departamento_id', 'superficie_sembrada_ha',
       'superficie_cosechada_ha', 'produccion_tm', 'rendimiento_kgxha'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cultivo                  1044 non-null   str
 1   anio                     1044 non-null   int64
 2   campania                 1044 non-null   str
 3   provincia                1044 non-null   str
 4   provincia_id             1044 non-null   int64
 5   departamento             1044 non-null   str
 6   departamento_id          1044 non-null   int64
 7   superficie_sembrada_ha   1044 non-null   int64
 8   superficie_cosechada_ha  1044 non-null   int64
 9   produccion_tm            1044 non-null   int64
 10  rendimiento_kgxha        1044 non-null   int64
dtypes: int64(7), str(4)
memory usage: 89.8 KB

In [9]:
df.describe()

,anio,provincia_id,departamento_id,superficie_sembrada_ha,superficie_cosechada_ha,produccion_tm,rendimiento_kgxha
count,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000,1044.000000
mean,1997.018199,50.206897,50276.487548,8837.775862,7010.222222,23931.875479,2999.870690
std,15.878815,11.058084,11038.772141,6378.618087,5538.221666,24417.274761,1559.803593
min,1970.000000,18.000000,18084.000000,4.000000,0.000000,0.000000,0.000000
25%,1983.000000,54.000000,54021.000000,4216.000000,2925.500000,5908.000000,1684.750000
50%,1997.000000,54.000000,54056.000000,7500.000000,5650.000000,15193.500000,2396.000000
75%,2011.000000,54.000000,54091.000000,11685.750000,9513.750000,32882.500000,4400.000000
max,2024.000000,54.000000,54119.000000,27320.000000,24199.000000,113738.000000,8100.000000

In [15]:
df.isnull().sum()

cultivo                    0
anio                       0
campania                   0
provincia                  0
provincia_id               0
departamento               0
departamento_id            0
superficie_sembrada_ha     0
superficie_cosechada_ha    0
produccion_tm              0
rendimiento_kgxha          0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.dtypes

cultivo                      str
anio                       int64
campania                     str
provincia                    str
provincia_id               int64
departamento                 str
departamento_id            int64
superficie_sembrada_ha     int64
superficie_cosechada_ha    int64
produccion_tm              int64
rendimiento_kgxha          int64
dtype: object