In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv("../data/yerba-mate-1970-2024.csv", encoding="latin-1")

df.head()

,cultivo,anio,campania,provincia,provincia_id,departamento,departamento_id,superficie_sembrada_ha,superficie_cosechada_ha,produccion_tm,rendimiento_kgxha
0,yerba mate,1970,1969/1970,Corrientes,18,Ituzaingó,18084,3470,1106,2375,2147
1,yerba mate,1970,1969/1970,Corrientes,18,Santo Tomé,18168,5205,1661,3564,2146
2,yerba mate,1970,1969/1970,Misiones,54,Apóstoles,54007,11784,3052,5150,1687
3,yerba mate,1970,1969/1970,Misiones,54,Cainguás,54014,6078,1566,3568,2278
4,yerba mate,1970,1969/1970,Misiones,54,Candelaria,54021,3298,872,1020,1170

In [3]:
conexion = sqlite3.connect("../data/yerba_mate.db")

In [4]:
df.to_sql("produccion", conexion, if_exists="replace", index=False)

1044

In [5]:
query = "SELECT * FROM produccion LIMIT 5"

resultado = pd.read_sql(query, conexion)

resultado

,cultivo,anio,campania,provincia,provincia_id,departamento,departamento_id,superficie_sembrada_ha,superficie_cosechada_ha,produccion_tm,rendimiento_kgxha
0,yerba mate,1970,1969/1970,Corrientes,18,Ituzaingó,18084,3470,1106,2375,2147
1,yerba mate,1970,1969/1970,Corrientes,18,Santo Tomé,18168,5205,1661,3564,2146
2,yerba mate,1970,1969/1970,Misiones,54,Apóstoles,54007,11784,3052,5150,1687
3,yerba mate,1970,1969/1970,Misiones,54,Cainguás,54014,6078,1566,3568,2278
4,yerba mate,1970,1969/1970,Misiones,54,Candelaria,54021,3298,872,1020,1170

In [6]:
query = """
SELECT provincia, SUM(produccion_tm) as total_produccion
FROM produccion
GROUP BY provincia
"""

resultado = pd.read_sql(query, conexion)

resultado

    provincia  total_produccion
0  Corrientes           3240426
1    Misiones          21744452

In [7]:
query = """
SELECT departamento, SUM(produccion_tm) as total_produccion
FROM produccion
GROUP BY departamento
ORDER BY total_produccion DESC
LIMIT 10
"""

resultado = pd.read_sql(query, conexion)

resultado

                    departamento  total_produccion
0                          Oberá           3257827
1                    San Ignacio           2380630
2                     Santo Tomé           2250790
3        General Manuel Belgrano           2102601
4                      Apóstoles           2034015
5                       Cainguás           1746570
6                        Guaraní           1377518
7  Libertador General San Martín           1367368
8                     Montecarlo           1058331
9                       Eldorado           1028813

In [8]:
query = """
SELECT anio, SUM(produccion_tm) as produccion_total
FROM produccion
GROUP BY anio
ORDER BY anio
"""

resultado = pd.read_sql(query, conexion)

resultado

    anio  produccion_total
0   1970             76788
1   1971             90460
2   1972            126714
3   1973            150963
4   1974            134529
5   1975            142308
6   1976            121135
7   1977            127167
8   1978            133436
9   1979            135200
10  1980            134813
11  1981            139745
12  1982            161371
13  1983            136210
14  1984            181625
15  1985            154469
16  1986            155740
17  1987            131995
18  1988            137401
19  1989            144838
20  1990            155830
21  1991            160761
22  1992            172455
23  1993            221321
24  1994            240414
25  1995            260718
26  1996            269970
27  1997            281573
28  1998            286770
29  1999            703448
30  2000            670399
31  2001            684597
32  2002            695400
33  2003            775591
34  2004            749200
35  2005            782801
36  2006            787900
37  2007            816600
38  2008            730190
39  2009            741686
40  2010            804458
41  2011            775600
42  2012            718190
43  2013            692770
44  2014            849825
45  2015            809100
46  2016            806936
47  2017            690100
48  2018            809302
49  2019            837054
50  2020            813454
51  2021            882047
52  2022            829299
53  2023            775032
54  2024            987180

In [9]:
conexion.close()